### ISSUE TITLE
Add method to LDESinLDP and VLIL that checks the existance of the LIL

### ISSUE THREAD

**Issue by woutslabbinck** [woutslabbinck/VersionAwareLDESinLDP#16]
e.g. a method `exists()` in both classes that returns a `Status` Enum

```typescript
Enum Status{
EXISTENT
NONEXISTENT
INVALID
)
```

**Comment by woutslabbinck** [comment]
After an online discussion with @TomWindels and @argahsuknesib, we propose to change the initial design (which is an Enum) to an Interface which works as a [bit field](https://en.wikipedia.org/wiki/Bit_field) for an LDES in LDP.

The proposed values of this Interface are the following:
| Flag     | Semantics                                                    |
| -------- | ------------------------------------------------------------ |
| Found    | Whether the LDES in LDP is reachable on the internet. Is false/0 when you cannot reach it due to internet connection or due to having no write permissions |
| Valid    | Whether the representation of a GET request can be parsed to (versioned) LDES in LDP Metadata |
| Writable | Whether the LDES in LDP root container can be written to **???** @Tom is this correct? |
| Empty    | Whether the LDES in LDP contains any members. We consider the LDES in LDP empty if there is one relation/fragment/bucket which has 0 resources. |
| Full     | Whether the LDES in LDP is considered full according through the retention policy. Action MUST be undertaken based on this flag (how is up to the implementer) |

**Comment by TomWindels** [comment]
There are a couple of changes I'd think would improve this further:
`Found` - instead of no write permissions (which is already checked for by `Writable` in these changes), it would refer to non-existing only (either web host/internet (connectivity)/similar related. This could then be used as a valid status to initialize a new LiL
`Writable` - This is what I think would be what it represents (write permissions to .meta and its children recursively)

**Comment by woutslabbinck** [comment]
#19 implements the `Found`, `Valid`, `Writable` and `Empty` flags.
#20 will allow `Full` to be implemented.

**Comment by woutslabbinck** [comment]
After an offline discussion with @TomWindels, we've decided to lower the priority of implementing `Full` to the status functionality.

Therefore, I'll close this issue.

When the priority of the `Full` Status is high, a new issue can be created or this issue can be reopened.
