### ISSUE TITLE
Feature Request : Implementing a function to get the resources of the last X duration.

### ISSUE THREAD

**Issue by argahsuknesib** [woutslabbinck/VersionAwareLDESinLDP#26]
Currently, the readAllMemebers function returns a stream of resources in a specific time range. However, in a streaming scenario it will be useful to specify the time range and get the resources in that time range. So that, when the LIL pod is updated with new resources, the function streams out the new resources.

**Comment by woutslabbinck** [comment]
So, if I understand correctly, you want a kind of listener to the LIL that returns members when it gets updated, right?

Behaviour of this listener would be as follows:
1. listener listens to a given LDES
2. members gets added to LDES
3. listener spits out new member

**Comment by argahsuknesib** [comment]
I would need a readable stream as an output from a function, where I specify a time duration of X minutes / hours, so that I can read the events happened in the last X minutes. So that, if a LIL is being continuously populated with new resources, I always have a stream of events that happened in last X minutes.

This can be done by reading the time of the last updated resource, and then `readingAllMembers` which are in the slot of  
```
time (last updated resource) - time (X as provided)
```
in the function.

**Comment by woutslabbinck** [comment]
I will create a function `readLastMembers(amount: integer): Promise<Readable>`, where the output is a memberstream.

On that stream, you can always write a `Transform` that filters out members which do not fall in your duration.
