### ISSUE TITLE
performance issues while reading the files with the readMembers function.

### ISSUE THREAD

**Issue by argahsuknesib** [woutslabbinck/VersionAwareLDESinLDP#36]
Hello,
 
I am using the [0.3.0-alpha](https://www.npmjs.com/package/@treecg/versionawareldesinldp/v/0.3.0-alpha.0) version of the library to support the metadata description with the GTE relations to describe the resources at the fragment level of the LDES in LDP.

However, the latency to read the files has reduced. 
For example, to read one resource with 10 members inside it is taking around 13 seconds. 

The script to reproduce the result is,

```ts
import {LDESinLDP, LDPCommunication} from "@treecg/versionawareldesinldp";

async function main(){
    let ldes_url = "http://n061-14a.wall2.ilabt.iminds.be:3000/participant6/data/";
    let time_start = new Date();
    let communication = new LDPCommunication();
    let ldes_in_ldp = new LDESinLDP(ldes_url, communication);
    let member_count = 0;

    let members = await ldes_in_ldp.readAllMembers(new Date("2023-11-15T08:48:41.682Z"), new Date("2023-11-15T08:48:43.401Z"));
    members.on('data', (member) => {
        member_count++;
    });
    members.on('end', () => {
        let time_end = new Date();
        let time_diff = time_end.getTime() - time_start.getTime();
        console.log(`Read ${member_count} members in ${time_diff/1000} s`);
    });
}

main();
```

The first 2 resources of the container http://n061-14a.wall2.ilabt.iminds.be:3000/participant6/data/1700038121682/ contains the relevant members for the window described in the script.

What do you think could be the bottleneck for the performance?

**Comment by woutslabbinck** [comment]
I just tried this script myself and it took a tenth of what you claim:
```sh
# first run
Read 12 members in 1.718 s
# second run
Read 12 members in 1.478 s
```

So I am not sure what the problem could be that it takes 13 seconds.
